matrix:
  include:
    # Linux / Python 3
    - os: linux
      language: python
      python: "3.6"
      dist: xenial
      sudo: required

cache:
  directories:
    - .cache

addons:
  apt:
    update: true

install:
  - ./ci/travis.sh setup

script:
  - ./ci/travis.sh build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: A3GAXqvj6WKeMnnib53ypyh/o70H4KjF32fMZeUhOW5gUzQkna3+Lkju35paLfE7dWIfIQLWQgMOT7lc/gw8oE2MuSORU3Y8/M4l9/1cfIGWTXHS0I2hI7C8hUi2zBREv7nUB+g6kGdQGsVhZx2oIWrJGzSbjL8rit57C3E+Mc+J7UULZjQ7GYqCkLNNRJpkpUcCuCVBSYG+50ZDT/swCAHgpLAGs+xlxGG9MV7fP9AR2sB3dzhvtnHuVe+nHtaYglayGtnLcfqVg3ztw3WMHbadr11OuYBl3CdT5f6MlZjCCG4Trb5x+tynLtb4qC4tSXI2wgw8s6P1p7Iv89kWkP42ZC/N2Y/trvr6cVnCLFnT4Fm24I/cdM5vQopufdst0lJn53OHkNefwkZIS0U/rTMWRJHYvKEORxPNYOcJEvbsA9OmneNWscSy8pz3pzvSd9zaDdk8D8dFdEvnJGl0UwzYya6pEnly0iWkZkPg6fC7e0TtS84FffQOoBorlIh+ZViQ4dD3MRb6lsNDSo+hhOP46HcTbFYg56NwYQ5kFruXL1DWT/wWlTDJ8FZKgj5AtFRVMOvrxOfSXXBdU+auTLzy0sVJFTEpwT7MmvLtR738aNewXa2momcB/N+6Lp1xQ+w6+0qkW9+/hAOKfJ7cLGjswsi8lpARWMtpxNdAphg=
  draft: true
  file_glob: true
  file:
    - "dist/*.AppImage"
    - "dist/*.tar.gz"
    - "dist/*.whl"
  on:
    tags: true
