site_name: Plover
theme:
  #name: "readthedocs"
  name: "material"
  features:
    #- navigation.tracking
    - navigation.instant
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search
  - mkdocstrings:
      watch:
        - plover
